name: Site Reliability
on: 
  workflow_dispatch:
  push:
    branches: 
      - master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'
jobs:
  crawl_for_broken_links:
    runs-on: ubuntu-latest
    name: Broken-Links-Crawler
    steps:
    - name: Debug Action
      uses: hmarr/debug-action@v1.0.0
    - name: Checking links
      id: checking
      uses: ScholliYT/Broken-Links-Crawler-Action@v3
      with:
        website_url: 'https://tomstein.me'
        exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://twitter.com'
        verbose: 'true'
        max_retry_time: 30
        max_retries: 5
  
  send-email:
    needs: crawl_for_broken_links
    runs-on: ubuntu-latest
    steps:
      - name: Download broken links report
        uses: actions/download-artifact@v4
        with:
          name: broken-links-report

      - name: Send email with report
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "Broken Links Report"
          body: "Please find the attached broken links report."
          to: sumeet@techbytesfoundation.org
          from: sumeet@techbytesfoundation.org
          attachments: broken-links.txt
